### ISSUE TITLE
[Unichristus] Postagem de agradecimento

### ISSUE THREAD

**Issue by alynnefs** [pyladiesfortaleza/organizacao-geral#108]

**Comment by AndyFernandes** [comment]
✨ Atenção ao momento de agradecimento aos nossos apoiadores/patrocinadores que estão fazendo esse evento acontecer! 💛

Gostaríamos de expressar nossa sincera gratidão à @unichristus, nosso apoiador principal do evento Django Girls! 💖🤩

🏛 Com uma trajetória marcada pela excelência, a Unichristus se destaca como a melhor instituição particular do Ceará, segundo o IGC do MEC. Com cinco campsi em Fortaleza e a Faculdade Christus no Eusébio, a Unichristus se compromete em oferecer educação superior de qualidade, sempre pautada em ensino, pesquisa e extensão.

Acreditamos que, juntos, podemos formar profissionais capazes de gerar um impacto positivo na sociedade. Muito obrigado por acreditarem em nossa missão e por nos apoiar nessa jornada! ✨

🔗 Para saber mais sobre a Unichristus, acesse: unichristus.edu.br e siga as novidades no Instagram @unichristus!

Não vai ficar fora dessa, né?! Fica ligada no nosso Instagram para acompanhar mais informações do evento! 🫰🏻🫶🏼

Vamos juntos fazer deste evento um sucesso! 🚀

📅  28 de setembro de 2024
📍 Unichristus - Campus Dom Lui

**Comment by AndyFernandes** [comment]
![Image](https://github.com/user-attachments/assets/acdc0ffc-3fe6-42a7-8574-19ea360384b3)
