### ISSUE TITLE
[PyBar] Criar arte

### ISSUE THREAD

**Issue by alynnefs** [pyladiesfortaleza/organizacao-geral#64]

**Comment by alynnefs** [comment]
@felurye desculpa te dar mais trabalho 👼🏼

**Comment by felurye** [comment]
[Canva com a arte](https://www.canva.com/design/DAGLb9tZg1g/Kt_MrgWCY34sfjnkvv_yGg/edit?utm_content=DAGLb9tZg1g&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

**Comment by felurye** [comment]
[Artes para os Stories](https://www.canva.com/design/DAGLcSYrYis/iP22N0Xy6WO6KCjXenxEzQ/edit?utm_content=DAGLcSYrYis&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
