### ISSUE TITLE
[EBM QUINTTO] Agradecimento nas redes sociais

### ISSUE THREAD

**Issue by alynnefs** [pyladiesfortaleza/organizacao-geral#91]

**Comment by AndyFernandes** [comment]
✨ Atenção ao momento de agradecimento aos nossos apoiadores/patrocinadores que estão fazendo esse evento acontecer! 💛

💖 Gostaríamos de expressar nossa sincera gratidão à @ebmquintto, nosso patrocinador do evento Django Girls! 🤩

🏛 A EBM Quintto é resultado da fusão entre a experiência da EBM Novotempo Propaganda e a visão inovadora da Quintto Comunicação. Desde 2011, essa combinação tem gerado transformação, tornando a EBM Quintto uma das maiores agências do Nordeste, com uma equipe criativa e premiada.

🎯 Acreditamos que a comunicação eficaz é essencial para o sucesso de qualquer projeto. Muito obrigado, EBM Quintto, por acreditarem em nossa missão e por nos apoiar nessa jornada! ✨

🔗 Para saber mais sobre a EBM Quintto, acesse: ebmquintto.com.br e siga as novidades no Instagram @ebmquintto!

🫰🏻 Não vai ficar fora dessa, né?! Fica ligada no nosso Instagram para acompanhar mais informações do evento! 🫶🏼

📅 28 de setembro de 2024
📍 Unichristus - Campus Dom Luis

**Comment by AndyFernandes** [comment]
![Image](https://github.com/user-attachments/assets/d736fb8d-ca9c-4a61-af17-1eb05c141643)
