### ISSUE TITLE
[PSF] Agradecimento nas redes sociais

### ISSUE THREAD

**Issue by alynnefs** [pyladiesfortaleza/organizacao-geral#94]

**Comment by AndyFernandes** [comment]
✨ Atenção ao momento de agradecimento aos nossos apoiadores/patrocinadores que estão fazendo esse evento acontecer! 💛

💖 Gostaríamos de expressar nossa sincera gratidão à @thepsf, nosso apoiador principal do evento Django Girls! 🤩

🏛 A Python Software Foundation é a organização por trás da linguagem de programação Python, dedicada a criar um ambiente que possibilite o crescimento e a prosperidade da comunidade Python. Eles garantem a distribuição gratuita do Python e protegem sua propriedade intelectual, promovendo estabilidade para todos os usuários e contribuidores.

🎯 Acreditamos que, juntos, podemos construir um futuro melhor para todos os apaixonados por programação. Muito obrigado, PSF, por acreditarem em nossa missão e por nos apoiar nessa jornada! ✨

🔗 Para saber mais sobre a Python Software Foundation, acesse: python.org/psf e siga as novidades no Instagram @thepsf!

🫰🏻 Não vai ficar fora dessa, né?! Fica ligada no nosso Instagram para acompanhar mais informações do evento! 🫶🏼

📅 28 de setembro de 2024
📍 Unichristus - Campus Dom Luis

**Comment by AndyFernandes** [comment]
![Image](https://github.com/user-attachments/assets/508a1f0b-c47e-4186-be01-6d7b19ea1012)
