### ISSUE TITLE
[DSF] Agradecimento nas redes sociais

### ISSUE THREAD

**Issue by alynnefs** [pyladiesfortaleza/organizacao-geral#97]

**Comment by AndyFernandes** [comment]
✨ Atenção ao momento de agradecimento aos nossos apoiadores/patrocinadores que estão fazendo esse evento acontecer! 💛

💖 Gostaríamos de expressar nossa sincera gratidão à @djangosf, nosso patrocinador principal do evento Django Girls! 🤩

🏛 A Django Software Foundation é uma organização sem fins lucrativos que apoia o desenvolvimento da framework Django, promovendo eventos, encontros e iniciativas que fortalecem a comunidade de desenvolvedores.

🎯 Com o apoio da DSF, conseguimos avançar na divulgação e utilização do Django, criando oportunidades para todos os apaixonados por tecnologia. Muito obrigado, DSF, por acreditarem em nossa missão e por nos apoiar nessa jornada! ✨

🔗 Para saber mais sobre a Django Software Foundation, acesse: djangoproject.com/foundation e siga as novidades no Instagram @djangosf!

🫰🏻 Não vai ficar fora dessa, né?! Fica ligada no nosso Instagram para acompanhar mais informações do evento! 🫶🏼

📅  28 de setembro de 2024  
📍 Unichristus - Campus Dom Luis

**Comment by AndyFernandes** [comment]
![Image](https://github.com/user-attachments/assets/84b65a67-1e34-4676-be68-581fd98b1151)
